#!/usr/bin/env python3
"""Convert a PEM CA bundle into a DER blob and Rust index file.

Usage:
    python3 scripts/gen_ca_bundle.py /tmp/cacert.pem

Outputs:
    libs/libbreenix/src/x509/ca-certificates.der  -- concatenated DER certs
    libs/libbreenix/src/x509/ca_index.rs           -- Rust (offset, length) index
"""

import base64
import os
import sys


def extract_der_certs(pem_path: str) -> list[bytes]:
    """Extract DER-encoded certificates from a PEM file."""
    certs = []
    in_cert = False
    b64_lines: list[str] = []

    with open(pem_path, "r") as f:
        for line in f:
            line = line.strip()
            if line == "-----BEGIN CERTIFICATE-----":
                in_cert = True
                b64_lines = []
            elif line == "-----END CERTIFICATE-----":
                in_cert = False
                b64_data = "".join(b64_lines)
                der = base64.b64decode(b64_data)
                certs.append(der)
            elif in_cert:
                b64_lines.append(line)

    return certs


def write_der_blob(certs: list[bytes], out_path: str) -> list[tuple[int, int]]:
    """Write concatenated DER blob and return index of (offset, length)."""
    index = []
    offset = 0

    with open(out_path, "wb") as f:
        for der in certs:
            f.write(der)
            index.append((offset, len(der)))
            offset += len(der)

    return index


def write_rust_index(index: list[tuple[int, int]], out_path: str) -> None:
    """Write the Rust source file with the CA_CERTS_INDEX constant."""
    with open(out_path, "w") as f:
        f.write(
            "/// Auto-generated index of (offset, length) for each root CA in ca-certificates.der\n"
        )
        f.write(
            "/// Generated by scripts/gen_ca_bundle.py -- DO NOT EDIT BY HAND\n"
        )
        f.write(
            "pub static CA_CERTS_INDEX: &[(usize, usize)] = &[\n"
        )
        for offset, length in index:
            f.write(f"    ({offset}, {length}),\n")
        f.write("];\n")


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <cacert.pem>", file=sys.stderr)
        sys.exit(1)

    pem_path = sys.argv[1]
    if not os.path.isfile(pem_path):
        print(f"Error: {pem_path} not found", file=sys.stderr)
        sys.exit(1)

    # Determine output directory relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    x509_dir = os.path.join(repo_root, "libs", "libbreenix", "src", "x509")

    der_path = os.path.join(x509_dir, "ca-certificates.der")
    index_path = os.path.join(x509_dir, "ca_index.rs")

    # Extract certs
    certs = extract_der_certs(pem_path)
    print(f"Found {len(certs)} root CA certificates")

    # Write DER blob
    index = write_der_blob(certs, der_path)
    total_size = sum(length for _, length in index)
    print(f"Wrote DER blob: {der_path} ({total_size} bytes)")

    # Write Rust index
    write_rust_index(index, index_path)
    print(f"Wrote Rust index: {index_path} ({len(index)} entries)")


if __name__ == "__main__":
    main()
