name: Ring‑3 Tests

on:
  push:
    paths:
      - 'kernel/**'
      - 'userspace/**'
      - 'xtask/**'
      - '.github/workflows/ring3-tests.yml'
  pull_request:

jobs:
  ring3-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      CARGO_UNSTABLE_BINDEPS: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-06-24
          override: true
          target: x86_64-unknown-none
          components: rust-src, llvm-tools-preview

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 ovmf nasm

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build userspace tests
        run: |
          # Add LLVM tools to PATH
          export PATH="$PATH:$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/bin"
          cd userspace/tests
          ./build.sh

      - name: Ring‑3 smoke test
        run: cargo run -p xtask -- ring3-smoke

      - name: Ring‑3 ENOSYS negative test
        run: cargo run -p xtask -- ring3-enosys

      - name: Upload QEMU logs if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: qemu-serial-logs
          path: |
            target/xtask_ring3_smoke_output.txt
            target/xtask_ring3_enosys.txt