name: Ring-3 ENOSYS Test

on:
  pull_request:
    paths:
      - 'kernel/**'
      - 'userspace/**'
      - 'tests/**'
      - 'xtask/**'
      - '.github/workflows/ring3-enosys.yml'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ring3-enosys:
    name: Test ENOSYS syscall handling
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, llvm-tools-preview

      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      
      - name: Install rust-objcopy
        run: |
          # Install llvm-tools-preview which includes rust-objcopy
          rustup component add llvm-tools-preview
          # Add cargo binutils for easier access to rust-objcopy
          cargo install cargo-binutils || true
          # Ensure rust-objcopy is in PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$(rustc --print sysroot)/lib/rustlib/$(rustc -vV | sed -n 's|host: ||p')/bin" >> $GITHUB_PATH

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils

      - name: Build userspace tests
        run: |
          cd userspace/tests
          # Build all userspace test binaries required by the kernel
          ./build.sh || echo "Warning: Some userspace tests failed to build"

      - name: Build kernel with test features
        run: cargo build --package kernel --release --features "testing,external_test_bins"

      - name: Run ENOSYS integration test
        run: |
          cargo test --test ring3_enosys_test --release
          echo "Integration test completed"

      - name: Build and run xtask ENOSYS test
        run: |
          cd xtask
          cargo build --release
          timeout 60 cargo run --release -- ring3-enosys || true
          # Allow failure but capture output

      - name: Check for test evidence in logs
        if: always()
        run: |
          echo "=== Checking for ENOSYS test evidence ==="
          if [ -f target/xtask_ring3_enosys_output.txt ]; then
            echo "Found xtask output file"
            grep -E "ENOSYS|Invalid syscall|999" target/xtask_ring3_enosys_output.txt || echo "No ENOSYS markers found"
          fi
          if [ -d logs ]; then
            echo "Found logs directory"
            grep -E "ENOSYS|Invalid syscall|999" logs/*.log 2>/dev/null | head -20 || echo "No ENOSYS markers in logs"
          fi

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enosys-test-output-${{ github.run_number }}
          path: |
            target/xtask_ring3_enosys_output.txt
            target/shared_kernel_test_output.txt
            logs/*.log
          if-no-files-found: warn