name: Ring-3 ENOSYS Test

on:
  pull_request:
    paths:
      - 'kernel/**'
      - 'userspace/**'
      - 'tests/**'
      - 'xtask/**'
      - '.github/workflows/ring3-enosys.yml'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ring3-enosys:
    name: Test ENOSYS syscall handling
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, llvm-tools-preview

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils nasm

      - name: Build kernel with test features
        run: cargo build -p kernel --release --features "testing"

      - name: Run ENOSYS integration test
        run: |
          cargo test --test ring3_enosys_test --release
          echo "Integration test completed"

      - name: Build and run xtask ENOSYS test
        run: |
          cd xtask
          cargo build --release
          timeout 60 cargo run --release -- ring3-enosys || true
          # Allow failure but capture output

      - name: Check for test evidence in logs
        if: always()
        run: |
          echo "=== Checking for ENOSYS test evidence ==="
          if [ -f target/xtask_ring3_enosys_output.txt ]; then
            echo "Found xtask output file"
            grep -E "ENOSYS|Invalid syscall|999" target/xtask_ring3_enosys_output.txt || echo "No ENOSYS markers found"
          fi
          if [ -d logs ]; then
            echo "Found logs directory"
            grep -E "ENOSYS|Invalid syscall|999" logs/*.log 2>/dev/null | head -20 || echo "No ENOSYS markers in logs"
          fi

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enosys-test-output-${{ github.run_number }}
          path: |
            target/xtask_ring3_enosys_output.txt
            target/shared_kernel_test_output.txt
            logs/*.log
          if-no-files-found: warn