name: Test Sanity Check Branch

on:
  push:
    branches: [ sanity-check-happy-ring-3 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  test-userspace:
    name: Test Userspace Execution
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install QEMU and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86 nasm
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-06-24
        components: rust-src, llvm-tools-preview
        targets: x86_64-unknown-none
        
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build Breenix
      run: |
        rustup default nightly-2025-06-24
        cargo +nightly-2025-06-24 build --release
        
    - name: Run Breenix Test
      run: |
        # Run exactly as we do locally
        timeout 30 ./scripts/run_breenix.sh uefi -display none > test_output.log 2>&1 || true
        
    - name: Check for Userspace Success
      run: |
        echo "=== Checking for userspace execution success ==="
        # Find the most recent log file
        LATEST_LOG=$(ls -t logs/breenix_*.log | head -1)
        echo "Checking log file: $LATEST_LOG"
        
        if [ -f "$LATEST_LOG" ] && grep -q "USERSPACE OUTPUT: Hello from userspace" "$LATEST_LOG"; then
          echo "✅ USERSPACE EXECUTION SUCCESSFUL!"
          echo "Found userspace output in logs"
          exit 0
        else
          echo "❌ USERSPACE EXECUTION FAILED!"
          echo "Did not find expected userspace output"
          echo ""
          echo "=== Last 50 lines of kernel output ==="
          if [ -f "$LATEST_LOG" ]; then
            tail -50 "$LATEST_LOG"
          else
            echo "No log file found!"
            ls -la logs/
          fi
          exit 1
        fi
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          test_output.log
          logs/*.log